関電のデータを月毎に出力できるようにした。
naozin555/study_harada pull request #5
Opened 2020-04-25 14:21 UTC by naozin555

【上手くいってないところ】
・なるべく共通の部分は残そうとして，メソッドのオーバーライドをしてみたが，
　def file_open(self):　，　def input_data(self):　，　def sum_month(self, month):を
　オーバーライドすることになり，結局コード量が約2倍になってしまった。

【次やること】
・東電と関電のデータを同時に処理すること
　このサイトが参考になりそう
　[(https://teratail.com/questions/15486)]

【ブランチがぐちゃぐちゃになった経緯】
①feature1(前回までの内容)を間違えてmasterにマージしてしまった(気づかなかった)
②developからfeature2を作成した。
②今回の内容をfeature2にPRしようとしたら間違えてfeature1にpushしてしまった
　(PRは未実施)
③いろいろぐちゃぐちゃになっていることに気づいて，
　masterからdevelop1を作成し，develop1からfeature3を作成し，今回の内容をfeature3にPRした

2020-05-07 11:02 UTC, naozin555 commented
【更新内容】
・関西電力と東京電力の前処理をどちらもできるようにしました。
・なるべく似たようなメソッドを作らないように改良しました。
　具体的には，生データの構造だけが違うので，ファイルを開いてデータモデルに格納する部分だけ追加で記述しました。（Service.pyの144~173行のclass ServiceKansai(Service):）
　（また，前回はオーバーライドしたと記載したが，コードをよく見直すとオーバーライドではなく，ただ新しいメソッドを作っただけだった）

【今後の課題】
・前処理をするファイルの指定
　ファイル名からは東京電力のファイルなのか関西電力のファイルなのか分からない。
　しかし，プログラミングで前処理する前に，ファイル名をいちいち自分で変更しておくのは手間のような気もする。
　今後もしWebスクレイピング？という技術を使って自動でファイルをとってこれるなら，
　そのときにファイル名を指定して保存できるのであれば，この問題は解決する気がする。

・東京電力と関西電力のデータの比較に用いる数式
　数式を用いて比較できていない。

> 次の課題です。
以下、関西電力の需給実績も合わせて取り込み、東京電力の需給実績との比較を実施してください。
比較の数式は、自由に決めてもらってOKです。


　比較したいのは，メイン（７割以上を占める）となる発電方式である。
　今回着目したのは，東京電力は火力，関西電力は火力＋原子力がほぼ７割を超えているということ。
　ロジックとしては，割合が高いものから順に足していって，合計割合が７割を超えたらそれがメインの電源構成と判断する。東京電力と関西電力のメインの電源構成を比較した場合，東京電力管轄内では原子力発電が稼働していないため，火力だけで７割をまかなっているというストーリーを描いているがプログラミングでの実現の仕方がわからないので現在は表示の仕方だけ記述。
　なぜ実現の仕方が分からないかというと，データモデルの値はとってこれても，それが何を示すのかが判断できない。
　例：tokyo_data.thermalで77.01%という数値が取ってこれても，それが火力発電の割合だと逆に辿る方法が分からない。
　もしかしたら，データモデルを一度辞書に入れなおすとこの問題は解決するかもしれないが未着手。

・データモデルからのデータの取得の仕方
　現在のclass Compare(object):の176行目からのdef compare(self, tokyo_data, kansai_data):だと
　一番最後の2020年2月のデータが自動的に取得されてしまう。
　本当はselfにいれた年月の需給割合で比較をしたい。
　

2020-05-08 00:24 UTC, TsJazz27Sumin requested changes
>【ブランチがぐちゃぐちゃになった経緯】

いろいろ失敗してみると分かることも多いので、いい経験ですね。

>ロジックとしては，割合が高いものから順に足していって，合計割合が７割を超えたらそれがメインの電源構成と判断する。
>火力だけで７割をまかなっているというストーリーを描いているがプログラミングでの実現の仕方がわからないので現在は表示の仕方だけ記述。
>もしかしたら，データモデルを一度辞書に入れなおすとこの問題は解決するかもしれないが未着手。

比較対象期間の各項目のsumだけlist<map<string=項目名,int=sunの数値>>のオブジェクトに入れて、sumの多い順に並べ替えてから、
「割合が高いものから順に足していって，合計割合が７割を超えたらそれがメインの電源構成」判定をしてみてはどうでしょうか。

その足す過程で項目名をlistでもmapでも入れていけば、構成項目名が分かると思います。
並べ替えとかソートの処理は、自分でifとか使って作ってみると、アルゴリズムの勉強にもなるので良さそうです。

全体的にいい感じで成長しているように感じます 👍

2020-05-08 00:24 UTC, TsJazz27Sumin commented on service.py
> +class Compare(object):
[Should]

メソッドもCompare、クラスもCompareだと微妙なのでクラス名は、xxxAnalyzerとかにしてはどうでしょうか。

2020-05-08 00:24 UTC, TsJazz27Sumin commented on service.py
> +class ServiceKansai(Service):
いいですね。ちゃんと継承を使えてる。

2020-05-08 00:24 UTC, TsJazz27Sumin commented on service.py
> +                if re.search('^DATE_TIME', line):
[May]

headerが東電と関電で違うのでそれでファイルフォーマット判定をして、どっちのファイルかどうか判定も可能ですね。そもそもHPが分かれているので、今のように最初からわかっている前提でもOKです。

2020-05-08 11:17 UTC, naozin555 commented
この概念ですね！やってみます！
https://qiita.com/hainet/items/daab47dc991285b1f552
> 比較対象期間の各項目のsumだけlist<map<string=項目名,int=sunの数値>>のオブジェクトに入れて、

2020-05-09 02:20 UTC, TsJazz27Sumin commented
>この概念ですね！やってみます！
>https://qiita.com/hainet/items/daab47dc991285b1f552

そうですね、JavaとPythonという違いはありますが、やることは同じです〜。

2020-05-10 10:31 UTC, naozin555 commented
・ソートアルゴリズム構築中
　途中までソートできるという問題が発生中。
　ハマってしまっているが，繰り返しの回数などしょうもないことが原因のような気がする。

・Compareクラスの削除
　当初，PowerSupplyAnalyzerというクラス名にしてみたが，
　そもそも新しくクラスを作る必要がなかったので，Serviceクラスにmax_sort関数を定義することにした。
> メソッドもCompare、クラスもCompareだと微妙なのでクラス名は、xxxAnalyzerとかにしてはどうでしょうか。

・東電ファイルと関電ファイルの見分け方については未着手
> 最初からわかっている前提でもOKです。
　

2020-05-10 14:06 UTC, naozin555 commented
164行目に削除し忘れたコードsorted_data.update(tmp_dict)がたまたま残っていたので，反省点を記述。
sorted_dataを表示していたので，ソートが途中で終わったかのように見えていたが，配列は降順にソートできてきた。
間違い①
　辞書のupdateはリストのappendと違って，メソッド名のとおり既に同じキーがある場合にはそのバニューを上書きすることになるので，降順にならない。
　仮にupdateがappendと同じ働きをするとしても，160行目のfor文内にあることで，同じキーとバリューを何回も付け足してしてしまう可能性があるので降順にならない
> ・ソートアルゴリズム構築中
　途中までソートできるという問題が発生中

2020-05-11 00:45 UTC, TsJazz27Sumin commented
ソートアルゴリズムはいろいろあるのですが、今回はどれで実現しようとしていますかね。
https://qiita.com/r-ngtm/items/f4fa55c77459f63a5228

[大小比較](https://github.com/naozin555/study_harada/pull/5/files#diff-a534c3c8963e6e7695f1d2cd016b98c7R161)をするのはいいのですが、比較した値を適切な位置に設定できているのか、というとそうでもなさそうですね...!

2020-05-12 12:19 UTC, naozin555 commented
自分で作った処理の確認のためにprint()していた部分などは削除しましたが，
使わなくなったメソッド def display_month(self): も削除すべきでしょうか？
呼び出さなければいいだけなので，残しておくべきでしょうか？

2020-05-13 00:03 UTC, TsJazz27Sumin commented
>使わなくなったメソッド def display_month(self): も削除すべきでしょうか？
>呼び出さなければいいだけなので，残しておくべきでしょうか？

実際には、使用しなくなった処理は残しておく理由はないので消した方がいいのですが、
学習用のアプリケーションですしいいですよ。

2020-05-13 00:07 UTC, TsJazz27Sumin commented
マージしましょう！成長著しいですね。

2020-05-13 09:26 UTC, naozin555 commented
ありがとうございます！
マージします！

2020-05-13 09:28 UTC, merged